# poetry install --extras "ui llms-llama-cpp vector-stores-qdrant embeddings-huggingface"
server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  # Should be matching the selected model
  max_new_tokens: 512
  context_window: 3900
  tokenizer: meta-llama/Meta-Llama-3.1-8B-Instruct
  prompt_style: "llama3"

llamacpp:
  llm_hf_repo_id: mradermacher/Ichigo-llama3.2-3B-s-instruct-GGUF
  llm_hf_model_file: Ichigo-llama3.2-3B-s-instruct-GGUF

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: nomic-ai/nomic-embed-text-v1.5

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
